- .travis.yml
- doc/instructions/CONTRIBUTING.md
- doc/instructions/PRODUCTION.md
Make sure to pass password when executing ./test.sh.
Do not run ./test.sh CHANGEME in production, it requires to much privilege on a typical production system.
Simplify STATIC_ROOT and MEDIA_ROOT for nginx server as STOQS will likely be the only thing running on it.
> More refinement of PRODUCTION instructions

- stoqs/loaders/CANON/loadCANON_september2015.py
- stoqs/loaders/CANON/toNetCDF/makeLRAUVNetCDFs.sh
- stoqs/loaders/CANON/toNetCDF/makeRCpctdNetCDF.sh
- stoqs/loaders/CANON/toNetCDF/makeRCuctdNetCDF.sh
- stoqs/loaders/CANON/toNetCDF/pctdToNetcdf.py
Updated loadCANON_september2015.py to add LRAUV data (per Danelle), RCpctd and RCuctd data. Small changes to toNetCDF scripts and programs to create this data. 
We will need to work through the deployment directories and scripts to be able to run makeLRAUVNetCDFs.sh on the deployment machine. As Danelle predicted, I cannot run makeLRAUVNetCDFs.sh from my development system, for example. Assumes a deployment configuration. Do we need a mechanism to set environmental variables to point to data stores, or do we need separation of core STOQS vs MBARI specific code into two github projects?
> Update to loadCANON_september2015.py and associated scripts

- stoqs/loaders/CANON/loadCANON_may2015.py
- stoqs/loaders/CANON/loadCANON_os2015.py
add OA1 and OA2 mooring load to loadCANON_may2015.py and loadCANON_os2015.py
The underlying netCDF file is the same for all 2015 campaigns.
> add OA1 and OA2 to CANON may_2015 and OffSeason_2015

- stoqs/loaders/CANON/loadCANON_os2015.py
At request of waveglider team, added wg_Tiny data file that starts after September 2015 CANON. Extended definition of enddate to be 12 31 2015
> add wg_Tiny data after fall 2015 CANON. extend OffSeason to end of 2015.

- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/utils/Viz/KML.py
This problem was caused by overflow of data values in one of the Parameters in the database. This fix simply passes over attempts to get the min and max value for KML generation. The bad data can be seen in some of the activities in the statistics of nitrate (Parameter ID 38):
http://stoqs.shore.mbari.org:8000/stoqs_canon_september2015/api/activityparameter.html?parameter=38
There may be other problems resulting from these bad values being in the database. The ideal fix is to not load them in the first place, or to fix whatever problem is causing the overflow in the first place.
> Fix problem where sensor tracks wouldn't plot on map

- stoqs/loaders/CANON/loadCANON_os2016.py
OA2 mooring now in a new location, with THREDDS server, analogous to M1. Data is continuously updated, throughout deployment, instead of generated for each campaign.
> duane add OA2 mooring to load, new location

- stoqs/loaders/SampleLoaders.py
For fixing MolecularEcology february2012 load.
> Put quotes around the 'm' units (bug discovered after last commit)

- .travis.yml
- stoqs/stoqs/templates/stoqs/campaigns.html
- stoqs/stoqs/templates/stoqs/stoqsquery.html
Also, attempt to reduce X3DOM missing geometry error and cascading warnings by appending Shape to the scene only when needed.
> Keep navbar always left justified

- stoqs/utils/STOQSQManager.py
Fixes initial "AJAX request for summary data failed" problem that cropped up for http://stoqs.mbari.org:8000/stoqs_os2016.
> Return blank morelInfo if no nominal position for platform model

- stoqs/loaders/LakeMichigan/load_2016.py
The NetCDF file from https://www.ngdc.noaa.gov/mgg/greatlakes/michigan.html should be added to the stoqs/loaders directory so that altitude can be computed.
> Add X3D Terrain for Lake Michigan to the load

- stoqs/loaders/__init__.py
- stoqs/mbari_campaigns.py
- stoqs/utils/STOQSQManager.py
It's a bit embarrassing that [this bug](https://github.com/stoqs/stoqs/compare/master...MBARIMike:master#diff-cae62b16781823905eaf402f6b07288aL1112) has been the code for so long.
It causes spatial temporal queries of summary overview data to be much slower and causes incorrect display of Platforms and Parameters when the selection is zoomed in depth and time.
If convenient, data should be reloaded to fix existing databases.
> Fix setting of Activity min and max depths during load

- stoqs/loaders/CANON/__init__.py
See http://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server/4935945#4935945
> Use matplotlib's 'Agg' to avoid 'No module named _tkinter' error

- stoqs/loaders/CANON/loadCANON_september2016.py
add new M1 deployment. Note that data from earlier deployment would also need to be loaded for a full dataset.
bump range on roms_spray glider, to allow sufficient headroom.
> duane update to loadCANON_september2016.py

- stoqs/loaders/DAPloaders.py
- stoqs/loaders/__init__.py
This was a strange error to discover and fix.
I discovered it after adding AXIS_X, ..., ROT_Z variables to BED NetCDF files and then trying to load one of the new files after loading a file without these new variables. DAPloaders.py was setting the global_ignored_names to ignored_names to which the new variables were added. The bug was in this line:
```python
self.ignored_names += self.global_ignored_names
```
All beginning Python books warn about assigning lists this way: copy by address. So `self.global_ignored_names` ended up having all the new variable names added to it and then they became `self.ignored_names` on the 2nd Activity load.
> Fix error on loading 2nd Activity with previously ignored names 

- stoqs/loaders/CANON/__init__.py
The LRAUV models also needed to be translated by '-.55 -.35 -.45' as the export from SolidWorks did not have the center in the center of the vehicle. This was done directly to the files in http://stoqs.mbari.org/x3d/lrauv.
> Add scalefactor of 2 to the LRAUV models

- .travis.yml
A more careful examination of the travis-ci log shows that upgrading to Python 3.6 is a bit more involved; miniconda needs to be updated too. 
This development should happen on a separate branch so that all other necessary changes (provision.sh, requirements, code changes) can be made in concert without affecting master.
> Remove Python 3.6 from travis-ci

- stoqs/utils/Viz/animation.py
Noticed that there was one 'None' value in in roll data from http://dods.mbari.org/opendap/data/auvctd/surveys/2017/netcdf/Dorado389_2017_068_00_068_00_decim.nc.html. This fix replaces None values with 0.0 and prints a warning to the server log.
> Trap bad angles and give a warning

- requirements/base.txt
- stoqs/utils/Viz/plotting.py
Underlying upgrades of Matplotlib must have removed the black edge of the Sample location circles. This PR adds the `edgecolors='k'` argument to the `scatter()` calls.
> Add black edgecolor to scatter plot of Sample locations

- stoqs/config/settings/common.py
Previous addition to default_allowed_hosts of 'eth0' host was required for MBARI server, but 'eth0' doesn't exist on all OSs, e.g. CentOS 7 uses interface 'enp0s3'.
> Pass over ValueError if system doesn't have 'eth0' interface

- stoqs/loaders/CANON/__init__.py
- stoqs/loaders/CANON/loadCANON_april2017.py
add new platforms (gliders) to loadCANON_april2017 loader. add the platforms to __init__.py as needed. Deal with changes in netCDF variable names introduced by Fred B. to address IOOS conventions for netCDF by creating "new" platforms that have these new variables, while retaining the "old" platforms with the old variables that are used by legacy loaders.
> add platforms; deal with changes in platforms, loadCANON_april2017

- stoqs/loaders/CANON/toNetCDF/lrauvNc4ToNetcdf.py
I noticed that the standard_name attribute was being set to the variable name for some recent data, e.g.: http://dods.mbari.org/thredds/dodsC/LRAUV/tethys/realtime/cell-logs/20170417T021527/cell-Normal_i.nc.html. This fix adds a standard name lookup table for writing correct standard_name attributes. I tested this as much as I could on my development system.
@danellecline Do you think it's safe to merge this and pull to production?
> Add standard name lookup override for LRAUV variables

- stoqs/loaders/CCE/__init__.py
- stoqs/loaders/CCE/loadCCE_2015.py
- stoqs/loaders/__init__.py
The BIN ADCP NetCDF files are about 2 GB in size and the previous checkForValidData() would examine every data value to determine if there were any non-NaN data, which took a looong time.
> Add load of ADCP data to the CCE BIN - improve speed of valid data check

- README.md
- Vagrantfile
- doc/instructions/PYCHARM.md
- provision.sh
The /vagrant synced folder is now mounted using NFS which requires the user to enter the host OS's admin password during provisioning. This is likely a necessary annoyance as the NFS performance is much better and the advantages of being able to develop in PyCharm are worth it.
@danellecline @rkahnMBARI I think this is ready for you to use in a parallel VM. After this is merged please install into a 'stoqsvm_python3' folder following instructions at https://github.com/stoqs/stoqs/blob/python3/README.md and https://github.com/stoqs/stoqs/blob/python3/doc/instructions/PYCHARM.md
Thanks!
> Refine VM configuration and instructions for using PyCharm

- Vagrantfile
- provision.sh
- stoqs/contrib/analysis/crossproduct_biplots.py
Following suggestions made at https://www.jverdeyen.be/vagrant/speedup-vagrant-nfs/ the NFS attribute cache timeout is set to 5 minutes. From a terminal login to the VM an initial `git status` takes more than 30 seconds. While the attributes are cached it takes less than .2 seconds. So, a git status/add/commit/push session from the VM command line should be completed in 5 minutes to avoid frustration.
As the stoqsgit repository is actually now on the Host OS, a git session there won't have this problem (i.e. performance from PyCharm will be much better).
> Improve NFS performance

- stoqs/stoqs/templates/stoqs/stoqsquery.html
Should fix the Attribute filtering not working problem.
> Move stoqs-attributes class from <table> to <tr> elements - legacy Python

- stoqs/loaders/CANON/loadCANON_september2017.py
Francisco Chavez and team decided today to extend time scope of this campaign to include data collected to end of year. Also, here update the L_66 source to include the post turnaround netCDF file.
> update L_66 data source; update end date to end of year

- stoqs/loaders/CANON/toNetCDF/makeLRAUVNetCDFs.py
nc4 files for LakeMichigan should be created now with this on kraken2. Unclear why this stopped working though.
>  query start/end time directly from nc4 file instead of TDS server

- docker/requirements/base.txt
- stoqs/utils/Viz/plotting.py
Addresses https://github.com/stoqs/stoqs/issues/734
> Replace deprecated griddata() with 'equivalent' method from scipy.interpolate

- stoqs/loaders/CANON/loadCANON_fall2019.py
add wgTiny, OA1, OA2 moorings to CANON fall 2019 loader.  wgTiny is showing up as "wgSpare" on ODSS
> add wgTiny, OA1, OA2 moorings to CANON fall 2019 loader

- stoqs/loaders/CANON/__init__.py
I had wanted to do this for a while so that the name appeared in the mouseover in the STOQS UI. It finally became required once there were two identical file names from two different platforms:
```
[mccann@elvis LRAUV]$ find . -name 201909122002_201909122048_2S_scieng.nc
./triton/missionlogs/2019/20190912_20190912/20190912T200238/201909122002_201909122048_2S_scieng.nc
./pontus/missionlogs/2019/20190821_20190912/20190912T200257/201909122002_201909122048_2S_scieng.nc
```
> Prepend platform name to Activity name

- stoqs/utils/Viz/plotting.py
Here's the change that broke it:
https://github.com/stoqs/stoqs/commit/70fd4f5774b6f7c863a481d4ea6ffabc49dd3ec0#diff-8ee5cd3d2717129f859bfec989dbcc8ebbe7f0d8d5e84026c2a2598dc184f475R80
2.5 years ago!
> Revert back to 256 default num_colors, fixing nagging bug in changing colormaps

- stoqs/loaders/CANON/toNetCDF/lrauvNc4ToNetcdf.py
- stoqs/loaders/ECOHAB/load_2023.py
- stoqs/loaders/SampleLoaders.py
This is before reloading stoqs_ecohab_april2023 so that we get an accurate commit hash associated with the reload.
> Commit fixes made on production server.
