stoqs/stoqs

- .gitignore
- loaders/BEDS/loadBEDS_CanyonEvents.py
- stoqs/templates/stoqsquery.html
- utils/MPQuery.py
- utils/STOQSQManager.py
- utils/Viz/__init__.py
This pull request uses the X3DOM 1.6 new geospatial component capabilities for platformOrientation data. It should be pulled into production so that the BEDs team can visualize their data.
> Fixes BEDs data visualization

- stoqs/templates/stoqsquery.html
- utils/Viz/__init__.py
Needed for sharing BED visualization
> Replace HTML slider for PlatformOrientation playback with X3D TimeSensor

- stoqs/templates/stoqsquery.html
Oops. Meant to have this on the last PR.
> Change cycleInterval from 60 back to the actual real selection value

- Vagrantfile
- vagrant_readme.md
Can this command be put into Vagrantfile to be executed for only MacOS hosts?
> Fixed typo, md formatting

- provision.sh
- requirements/development.txt
- stoqs/loaders/ROVCTDloader.py
Added freetds prerequisite and fixed eos80 libraries
> Make loaders/ROVCTDloader.py work

- stoqs/contrib/notebooks/summarize_LOPC.ipynb
- stoqs/loaders/CANON/realtime/monitorLrauv_sep2015.sh
- stoqs/loaders/CANON/toNetCDF/makeLRAUVNetCDFs.sh
- stoqs/utils/Viz/__init__.py
1. 3D platform pitch angle adjustment to account for vertical exaggeration
2. Jupyter Notebook script that loads LOPC data in the new stoqs/contrib/Notebooks folder
3. Fix for monitorLrauv_sep2015.sh to accept an argument for the project directory
> Very miscellaneous commits

- stoqs/loaders/CANON/loadCANON_september2015.py
added WFuctd files and WFpctd to the loader. Incorporates change to make the filenames all consistent case upon transfer from WF to shore (kgomes).
> duane add WFuctd & WFpctd

- stoqs/loaders/CANON/loadCANON_september2015.py
- stoqs/loaders/CANON/toNetCDF/makeWFpctdNetCDF.sh
- stoqs/loaders/CANON/toNetCDF/makeWFuctdNetCDF.sh
added additional WFuctd and WFpctd data sets. updated makeWFuctdNetCDF and makeWFpctdNetCDF to reflect this campaign source (2015_Sep)
> duane add WFuctd and WFpctd loads

- .travis.yml
- README.md
- requirements/base.txt
- requirements/development.txt
- requirements/travis-ci.txt
- stoqs/utils/STOQSQManager.py
Travis-CI build appears to be working now after these multiple attempts to fix.
> Use intersection of platformsHavingModels and platforms_to_animate for 3D view

- stoqs/loaders/CANON/loadCANON_september2015.py
add dorado mission Dorado389_2015_285_00_285_00_decim.nc
> duane add dorado mission

- stoqs/loaders/CANON/loadCANON_september2015.py
add most recent dorado mission. tested on development system. 
improved layout in the dorado missions (deleted some tabs that came from somewhere...).
> duane add  Dorado389_2015_286_00_286_00_decim.nc

- stoqs/loaders/CANON/loadCANON_september2015.py
added new dorado mission 10/14/15, plus RC pctd and uctd missions from 10/8/15 and 10/12 - 10/14/2015.
there are some bottle files missing from pctd runs. I will check into that, but it ok to load what we have now.
> duane add dorado mission, and RC pctd and uctd missions

- stoqs/loaders/CANON/loadCANON_september2015.py
remove comments from OA1 and OA2. Now ready for production load. Removed unnecessary comments from load files regarding files already loaded.
> activate OA1 and OA2 load; remove unnecessary comments

- stoqs/loaders/CANON/realtime/Contour.py
- stoqs/loaders/CANON/realtime/monitorLrauv_os2015.sh
- stoqs/loaders/CANON/toNetCDF/lrauvNc4ToNetcdf.py
- stoqs/loaders/CANON/toNetCDF/makeLRAUVNetCDFs.py
- stoqs/loaders/DAPloaders.py
Changes in this pull request should fix any bugs associated with the creation of 10 second science data and loading of that data into the fall 2015 database.  Also includes bug fixes that caused failures in the plots for off-season LRAUV data.
> LRAUV netCDF and loader bug fixes

- requirements/base.txt
- requirements/development.txt
- stoqs/loaders/SampleLoaders.py
This should fix subsample load for NetTow and PlanktonPump data.
> Give a sample_name of '1' to all NetTow subsamples

- stoqs/loaders/CANON/realtime/monitorLrauv_os2016.sh
Removed echo and debugging for loader - this was a version I was debugging with. This is the correct version.
> Correct monitorLrauv script for 2016 off season

- doc/instructions/LOADING.md
- requirements/base.txt
- requirements/development.txt
- requirements/production.txt
- requirements/travis-ci.txt
- stoqs/loaders/load.py
Django==1.9.1 fails with debug_toolbar import error. Probably need to rebuild config files with django-cookiecutter for Django 1.9.
> Bumped version numbers

- stoqs/loaders/CANON/loadCANON_os2016.py
add L66 deployed 20151124 to os2016
> duane add L66 to os2016 loader

- stoqs/loaders/CANON/loadCANON_os2016.py
added January 13 2016 Rachel Carson pctd and uctd files to os2016 loader. deleted pctd and uctd files from 2015.
> duane add Jan 13 RC pctd and uctd to os2016

- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/utils/STOQSQManager.py
- stoqs/utils/Viz/__init__.py
To support Spatial -> 3D playback of BED data the platformAnimationDataValuesForX3D() method assembles only overlapping in time platform data. These changes do need to be tested for platform data that do overlap, for example LRAUV data for September 2015.
> Support multiple platform animation playback

- stoqs/stoqs/templates/stoqs/stoqsquery.html
Implemented at the VR Hackathon in SF
> Make 'Rift It' button work with the WebVR API for the DK2

- stoqs/stoqs/templates/stoqs/stoqsquery.html
webvr inputs work - need to properly place hand in scene and map to gvp postitions properly for movement control
> Added LeapMotion code. Changed 'Rift it!

- stoqs/utils/Viz/__init__.py
Fixes Dorado platform animation.
> Rotate about -X for BED platform, +X otherwise

- stoqs/loaders/OceanSITES/load_moorings.py
Fixes made during OceanSITES meeting in Southampton.
> Monkey patch coards functions and use local thredds_crawler

- stoqs/loaders/SampleLoaders.py
For fixing MolecularEcology february2012 load.
> Import specific model classes rather than 'as m'

- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/utils/STOQSQManager.py
Details about the Parameter now appear on mouseover.
> Add Parameter info to title of info-sign in UI

- stoqs/utils/Viz/__init__.py
Fixes bug where time gaps caused problems.
> Create equal interval times for platform animation

- provision.sh
- stoqs/loaders/DAPloaders.py
Addresses https://github.com/stoqs/stoqs/issues/306
> Upgrade GDAL to 2.1.0 in provision.sh

- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/stoqs/views/query.py
- stoqs/utils/MPQuery.py
- stoqs/utils/STOQSQManager.py
- stoqs/utils/utils.py
Allows selection/restriction of plotted data - useful for overlapping CCE data of different strides
> Add checkboxes to Activity names shown in Metadata -> NetCDF tab

- provision.sh
Addresses https://github.com/stoqs/stoqs/issues/312
> Update epel version and check for successful wget of it

- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/stoqs/views/query.py
- stoqs/utils/STOQSQManager.py
- stoqs/utils/Viz/__init__.py
This PR also limits the number of time points that can be delivered in a summary data request. Long duration high resolution platform animation data can exceed the memory capacity of even very large servers, so a new PA_MAX_POINTS variable has been defined with a value of 10000000 to ensure that summary requests either return with data and/or display an alert in the STOQS UI.
> Add Labels and ENU Axes checkboxes to 3D Platform animation

- stoqs/loaders/CANON/loadCANON_os2016.py
Update loadCANON_os2016 with Dorado loads, NPS34, L_662 deployments. Uncomment active assets for loads.
> add Dorado loads, NPS34, L_662 deployments

- stoqs/loaders/CANON/__init__.py
- stoqs/loaders/CANON/loadCANON_os2016.py
- stoqs/loaders/CANON/loadCANON_september2016.py
os2016. Add OA1 and update wgTiny platforms
september2016. add SG621 seaglider from KISS project, plus changes from os2016 (OA1 and wgTiny)
> update canon os2016 and september2016 loaders

- stoqs/loaders/CANON/loadCANON_september2016.py
implement compact enumeration of the netCDF file list for sg621.
> add SG621 loader

- stoqs/loaders/DAPloaders.py
Supports multiple sets of spatial/temporal coordinates in a file.
> Factor out _getCoordinates() and call for each variable

- stoqs/loaders/CANON/realtime/monitorLrauv.py
- stoqs/loaders/CANON/toNetCDF/lrauvNc4ToNetcdf.py
- stoqs/loaders/DAPloaders.py
- stoqs/loaders/LakeMichigan/monitorLrauv.py
- stoqs/loaders/LakeMichigan/monitorLrauv_2016.sh
Not 100% sure if this will work for the glider data, but I think it will.
> Added a standard_name for all LRAUV netCDFS coordinates and change to DAPLoader coordinate handling

- stoqs/loaders/__init__.py
Addresses https://github.com/stoqs/stoqs/pull/343#issuecomment-238363334
> First get_or_create() new parameters, then update descriptions

- stoqs/loaders/CANON/__init__.py
- stoqs/loaders/__init__.py
Addresses https://github.com/stoqs/stoqs/issues/361
> Fixes for --append loads

- stoqs/loaders/CANON/__init__.py
- stoqs/loaders/CANON/loadCANON_september2016.py
init:  --append update on OA1 and OA2 and L_662
loader: added L_667 deployment update
> duane update to __init__.py and loadCANON_september2016.py 

- stoqs/loaders/DAPloaders.py
This method can be used for more accurate Activity lookups, for example when appending data.
Addresses https://github.com/stoqs/stoqs/pull/365
> Factor out a getActivityName() method

- stoqs/loaders/CANON/__init__.py
- stoqs/loaders/DAPloaders.py
The DAPloaders module will modify the Activity name based on startdatetime and stride parameters set for the load. Queries for Activity lookup for purposes of appending data need to be done internal to Base_Loader class in DAPloaders.
Addresses https://github.com/stoqs/stoqs/pull/365
> Put logic for --append in DAPloaders

- stoqs/loaders/CANON/__init__.py
- stoqs/loaders/CANON/loadCANON_september2016.py
@duane-edgington It'd be great to get this rolled out to our production loads ASAP.
> Add simulated ROMS platforms to the load

- stoqs/loaders/CANON/realtime/monitorLrauv.py
- stoqs/loaders/CANON/realtime/monitorLrauv_sep2016.sh
- stoqs/loaders/CANON/toNetCDF/lrauvNc4ToNetcdf.py
- stoqs/loaders/LakeMichigan/Contour.py
- stoqs/loaders/LakeMichigan/__init__.py
- stoqs/loaders/LakeMichigan/monitorLrauv.py
https://github.com/stoqs/stoqs/pull/375
> LRAUV loader changes per updates to --append logic

- stoqs/loaders/CANON/loadCANON_september2016.py
Add OA2. location of the netCDF file had changed since last use of the file.
> add OA2 to loadCANON_september2016

- stoqs/loaders/CANON/loadCANON_september2016.py
> test of commit

- stoqs/loaders/CANON/loadCANON_september2016.py
correct wfiv16 series WF uctd and pctd. The syntax may require the two sets of uctd and pctd files to be loaded separately. 
corrected index on sg621 to load all data
minor fix to L_662 to include all data during this campaign
removed git test comment
> correct wfiv16 series WF uctd and pctd; correct index sg621

- provision.sh
Preparing provision script for also installing MB-System.
> Install GDAL only from source, install GMT from source, update versions

- stoqs/stoqs/templates/stoqs/stoqsquery.html
> Collapse any opened 3D control panels when going into Cardboard

- stoqs/stoqs/templates/stoqs/stoqsquery.html
Addresses https://github.com/stoqs/stoqs/issues/369
> Remove Cardboard button from Experimental area and give instruction

- stoqs/loaders/CANON/toNetCDF/makeLRAUVNetCDFs.sh
very minor change to simplify running of this script from year-to-year. updated to 2017 for good measure.
> added year argument to LRAUV netCDF generator

- provision.sh
> added line to update epel-release to latest version

- stoqs/utils/Viz/plotting.py
New method helps with revised code to properly pad animations that start after the earliest platform starts.
> Factor out an _append_animation_values() method

- stoqs/loaders/CANON/loadCANON_os2017.py
add platforms to offseason 2017 loader created by Danelle. L66 glider, mooring OA1, mooring OA2, waveglider Tiny.
> add l66, OA1, OA2, WGTiny to loadCANON_os2017.py

- stoqs/loaders/CANON/loadCANON_os2017.py
add second wgTiny deployment during this campaign period.
> update to add wgtiny deployment

- stoqs/loaders/MolecularEcology/load_dorado2009.py
- stoqs/mbari_campaigns.py
- stoqs/utils/Viz/plotting.py
For help in working on https://github.com/stoqs/stoqs/issues/495
> Use short 2009 Dorado mission to diagnose 3D platform animation issue

- stoqs/utils/Viz/plotting.py
Addresses https://github.com/stoqs/stoqs/issues/495
> Change the order of rotation transforms from roll, yaw, pitch to roll, pitch, yaw

- requirements/base.txt
- stoqs/utils/Viz/plotting.py
Applies to https://github.com/stoqs/stoqs/issues/495
> Replace roll, pitch, yaw orientation transforms with a single axis-angle transform

- stoqs/utils/Viz/plotting.py
This reverts commit a7ab11c6633939f7d2548c1c1c71c5d3d66e6411.
Applies to https://github.com/stoqs/stoqs/issues/495
After testing on production it appeared that the attitude of the vehicle was not as vertical as it should be. So this reverts back to the less efficient but more correct method.
> Revert "Replace roll, pitch, yaw orientation transforms with a single axis-angle transform

- stoqs/stoqs/tests/functional_tests.py
To help with https://github.com/stoqs/stoqs/issues/230
> Create test_contour_plots() functional test 

- stoqs/loaders/CANON/loadCANON_os2017.py
- stoqs/loaders/CANON/realtime/Contour.py
- stoqs/loaders/CANON/toNetCDF/lrauvNc4ToNetcdf.py
- stoqs/loaders/CANON/toNetCDF/makeLRAUVNetCDFs.py
- stoqs/loaders/CANON/toNetCDF/makeLRAUVNetCDFs.sh
Changes to support correct netCDF pitch/roll/yaw loads and removed outdated pupynere library which was causing weird interpolation errors since Aug. 2016.  Added new platform names where missing and matplotlib changes per package updates.
> LRAUV loader maintenance

- stoqs/stoqs/templates/stoqs/stoqsquery.html
> Add 'ROT Axis' checkbox

- stoqs/loaders/CANON/__init__.py
- stoqs/loaders/DAPloaders.py
This is so that we can plot data in the Temporal -> Parameter pane
> Add plotTimeSeriesDepth to the LRAUV loads

- .travis.yml
- README.md
- provision.sh
- requirements/base.txt
- stoqs/config/settings/common.py
- stoqs/contrib/analysis/__init__.py
- stoqs/contrib/analysis/classify.py
- stoqs/loaders/CANON/__init__.py
- stoqs/loaders/DAPloaders.py
- stoqs/loaders/SampleLoaders.py
- stoqs/loaders/__init__.py
- stoqs/loaders/loadTestData.py
- stoqs/loaders/seabird.py
- stoqs/stoqs/models.py
- stoqs/stoqs/tests/functional_tests.py
- stoqs/stoqs/tests/unit_tests.py
- stoqs/stoqs/views/__init__.py
- stoqs/stoqs/views/management.py
- stoqs/stoqs/views/query.py
- stoqs/stoqs/views/wms.py
- stoqs/utils/MPQuery.py
- stoqs/utils/PQuery.py
- stoqs/utils/STOQSQManager.py
- stoqs/utils/Viz/KML.py
- stoqs/utils/Viz/animation.py
- stoqs/utils/Viz/plotting.py
- stoqs/utils/encoders.py
- stoqs/utils/geo.py
- stoqs/utils/utils.py
Initial changes to build and use Python 3.6 in the Vagrant VM and to get passing on Travic-CI.
Applies to https://github.com/stoqs/stoqs/issues/523
> Convert to Python 3

- provision.sh
Also, temporarily clone branch python3.
> Upgrade to PostgreSQL 9.6 and PotGIS 2.3

- requirements/development.txt
- stoqs/stoqs/tests/functional_tests.py
- stoqs/utils/Viz/KML.py
Addresses https://github.com/stoqs/stoqs/issues/523
> Fixes after more testing on a fresh VM

- stoqs/loaders/CANON/loadCANON_os2017.py
add dorado data files and RC pctd and uctd data files to loadCANON_os2017.py
> update loadCANON_os2017.py Dorado files, RC files

- stoqs/loaders/CANON/loadCANON_os2017.py
add sample files. clean up previous file list.
> update loadCANON_os2017.py samples files

- stoqs/config/settings/common.py
- stoqs/stoqs/tests/functional_tests.py
- stoqs/stoqs/views/query.py
- stoqs/stoqs/views/wms.py
- stoqs/utils/STOQSQManager.py
- stoqs/utils/Viz/plotting.py
- test.sh
Addresses https://github.com/stoqs/stoqs/issues/417
> Use StaticServerTestCase to run functional tests

- stoqs/contrib/analysis/classify.py
- stoqs/loaders/DAPloaders.py
- stoqs/stoqs/tests/functional_tests.py
- stoqs/stoqs/views/app.py
- stoqs/utils/PQuery.py
- stoqs/utils/STOQSQManager.py
- stoqs/utils/Viz/plotting.py
Applies to https://github.com/stoqs/stoqs/issues/523
> Improve test coverage

- .pyup.yml
- requirements/base.txt
- requirements/development.txt
- requirements/production.txt
Applies to https://github.com/stoqs/stoqs/issues/523
> Bump minor version numbers

- stoqs/loaders/CANON/loadCANON_os2017.py
add 20170307 wgTiny deployment.
> loadCANON_os2017.py update with wgTiny deployment

- stoqs/loaders/CANON/loadCANON_april2017.py
start KISS CANON spring campaign loadCANON_april2017.py
> start KISS CANON spring campaign loadCANON_april2017.py

- docker/Dockerfile
- docker/Dockerfile-base
- docker/README.md
Mike:
OK, here's a PR to incorporate the initial set of files for dockerizing STOQS.
> initial sketch toward implementing #552

- stoqs/loaders/CANON/__init__.py
- stoqs/loaders/CANON/loadCANON_april2017.py
update color of sg539 with hope of it being more distinctive from sg621, 
add recent wgTiny data source
add individual slocum_nemesis data files. on my to-do list to try to generate these file names algorithmically instead of enumerating all them explictly, but that does not look easy...
> update color sg539, wgTiny data, slocum_nemesis data

- stoqs/loaders/__init__.py
First seen in April 2017 Nemesis data
> Skip over depths that are _FillValues

- stoqs/loaders/CANON/loadCANON_april2017.py
> update Dorado, nemesis, SG529, SG621, WFuctd, WFpctd datasets

- stoqs/loaders/CANON/loadCANON_april2017.py
add WFuctd, WFpctd, SG539, SG621, Dorado data files to loadCANON_april2017.py
> add WFuctd, WFpctd, SG539, SG621, Dorado data files

- stoqs/loaders/CANON/loadCANON_april2017.py
update SG621, SG539, WFpcdt, WFuctd in loadCANON_april2017.py
> update SG621, SG539, WFpcdt, WFuctd

- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/utils/Viz/plotting.py
Applies to #230 
Implemented the logic to plot the contour lines over a color map.
> Contour lines feature

- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/stoqs/tests/functional_tests.py
Applies to https://github.com/stoqs/stoqs/issues/230
> Fix functional_tests to test the new contour line plot feature

- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/stoqs/tests/functional_tests.py
- stoqs/utils/STOQSQManager.py
Applies to https://github.com/stoqs/stoqs/issues/230
> Tighten up 'Plot Data/Lines/Color' table headings and fix functional_tests.py

- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/stoqs/tests/functional_tests.py
- stoqs/utils/MPQuery.py
- stoqs/utils/STOQSQManager.py
- stoqs/utils/Viz/plotting.py
Applies to https://github.com/stoqs/stoqs/issues/230
> Allow plotting of contour lines separately without color plot

- .travis.yml
- doc/instructions/CONTRIBUTING.md
- doc/instructions/PRODUCTION.md
- provision.sh
- stoqs/config/settings/common.py
- stoqs/loaders/BEDS/loadBEDS_CanyonEvents.py
- stoqs/loaders/CANON/loadCANON_april2017.py
- stoqs/loaders/CANON/loadCANON_os2016.py
- stoqs/loaders/CANON/loadCANON_os2017.py
- stoqs/loaders/CANON/loadCANON_september2016.py
- stoqs/loaders/CANON/realtime/Contour.py
- stoqs/loaders/CANON/realtime/monitorLrauv.py
- stoqs/loaders/CANON/realtime/monitorLrauv_april2017.sh
- stoqs/loaders/CANON/toNetCDF/lrauvNc4ToNetcdf.py
- stoqs/loaders/CCE/__init__.py
- stoqs/loaders/CCE/loadCCE_2015.py
- stoqs/loaders/DAPloaders.py
- stoqs/loaders/LakeMichigan/load_2016.py
- stoqs/loaders/__init__.py
- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/stoqs/tests/functional_tests.py
- stoqs/stoqs/tests/unit_tests.py
- stoqs/stoqs/views/query.py
- stoqs/utils/MPQuery.py
- stoqs/utils/STOQSQManager.py
- stoqs/utils/Viz/plotting.py
- test.sh
Addresses https://github.com/stoqs/stoqs/issues/523
> Production instructions for python3

- stoqs/loaders/CANON/loadCANON_postSeason2017.py
- stoqs/mbari_campaigns.py
one new loader file and addition to mbari_campaigns.py
> create new postSeason2017 database

- README.md
- doc/instructions/CONTRIBUTING.md
- doc/instructions/DEVELOPMENT.md
- doc/instructions/LOADING.md
- doc/instructions/PRODUCTION.md
- doc/instructions/PYCHARM.md
- doc/instructions/TIDBITS
- doc/papers/README.md
- provision.sh
- stoqs/contrib/analysis/README
- stoqs/contrib/notebooks/CCE_BEDs_queries.ipynb
- stoqs/contrib/notebooks/classify_data.ipynb
- stoqs/contrib/notebooks/explore_BIOM_data_for_SIMZ.ipynb
- stoqs/contrib/notebooks/geospatial_selection_rovctd.ipynb
- stoqs/contrib/notebooks/pull_from_all_databases.ipynb
- stoqs/contrib/notebooks/summarize_LOPC.ipynb
- stoqs/loaders/CANON/loadCANON_postSeason2017.py
- stoqs/mbari_campaigns.py
- stoqs/stoqs/db_router.py
- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/stoqs/views/query.py
@danellecline @rkahnMBARI Please see https://github.com/MBARIMike/stoqs/blob/python3/doc/instructions/PYCHARM.md for my attempt to document configuring PyCharm to work with a stoqs VM. I plan to update the scripts and documentation here in the python3 branch to use /vagrant/dev instead of /home/vagrant/dev for the cloned stoqsgit working directory. This folder is automatically synced to the host OS which should make it easier to use PyCharm on the host OS.
> Document setup and make changes to easily use PyCharm for development

- stoqs/mbari_campaigns.py
A small syntax error was inhibiting data loading.
> Fixing syntax error

- stoqs/loaders/CANON/loadCANON_postSeason2017.py
- stoqs/mbari_campaigns.py
I am trying to push the typo fix to mbari_campaigns.py, and updates to loadCANON_postSeason2017.py to the repository.
Two merges are being added to my push by Git that I do not understand. I don't know how to decouple them from my update. They are not showing on my branch in my development system. 
If the merges are not desired, please advise on how I can rebase or whatever to try again.
> fix typo, update loadCANON_postSeason2017.py loader with Dorado

- stoqs/contrib/notebooks/create_timeline_plot.ipynb
@rkahnMBARI I think we are ready to incorporate plotting as shown in https://plot.ly/python/gantt/.
> Update create_timeline_plot Notebook

- stoqs/stoqs/templates/stoqs/stoqsquery.html
This PR eliminates a duplicate summary data request which was causing poor performance on production servers.
> Trigger X3D viewpoint parameters setting onUpdate and 3D tab click

- Vagrantfile
- stoqs/loaders/load.py
This Pull Request addresses https://github.com/stoqs/stoqs/issues/622
> Improve database loading performance

- stoqs/stoqs/templates/stoqs/stoqsquery.html
This should fix the broken Attribute filtering in the UI.
> Move stoqs-attributes class from <table> to <tr> elements

- stoqs/loaders/CANON/loadCANON_postSeason2017.py
add M1 deployment, and add wgTiny post deployment QC netCDF
> update lodCANON_postseason2017 M1 wgTiny

- stoqs/loaders/CANON/loadCANON_postSeason2017.py
add new dorado deployment postseason 2017
> add new dorado deployment postseason 2017

- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/utils/Viz/animation.py
Requested by CCE team so as to more easily visualize the different BED motions.
> Set X3D model Material colors to platform color 

- stoqs/loaders/CANON/loadCANON_september2017.py
- stoqs/mbari_campaigns.py
new loader file for CANON september 2017, plus update to mbari_campaigns.py to register this file in the database
> new campaign CANON september 2017

- stoqs/loaders/CANON/realtime/monitorLrauv.py
- stoqs/loaders/CANON/realtime/monitorLrauv_sep2017.sh
Renamed variables for sbd/cell data to shorter names, e.g. bin_mean_downwelling_photosynthetic_photon_flux_in_sea_water is PAR,  vertical_temperature_homogeneity_index is VTHI.
> LRAUV experiment loader for Fall 2017 CANON

- stoqs/loaders/CANON/loadCANON_september2017.py
add most recent dorado mission to loadCANON_september2017.py
> add dorado mission

- requirements/base.txt
- stoqs/loaders/DAPloaders.py
- stoqs/loaders/__init__.py
Applies to https://github.com/pydap/pydap/issues/132
> Upgrade to Pydap 3.2.2 and make fixes to loading code

- stoqs/stoqs/templates/stoqs/stoqsquery.html
Check for platformAnimation and include geometry in Shape
> Fix warnings and error in X3DOM's debug view

- stoqs/loaders/CANON/loadCANON_os2018.py
- stoqs/mbari_campaigns.py
new loader for offSeason 2018, plus log of the new loader in mbari_campaigns file
> new loader for offSeason 2018

- stoqs/loaders/CANON/loadCANON_os2018.py
- stoqs/mbari_campaigns.py
correct type in mbari_campaigns. activate the rest of the load commands. has the change from Danelle regarding lrauv directory
> update loader for offSeason 2018

- stoqs/loaders/CANON/loadCANON_os2018.py
update loadCANON_os2018.py with recent Dorado mission. Fix typo in description (not a campaign).
> update loadCANON_os2018.py Dorado mission

- stoqs/loaders/CANON/loadCANON_os2018.py
> upadates to loadCANON_os2018.py wgTiny

- README.md
> Fix master README.md following merge of python3 branch

- README.md
- provision.sh
> Some more touchups following the python3 merge

- requirements/base.txt
- requirements/development.txt
- requirements/production.txt
> Update requirements, all except for Django to 2.0

- Vagrantfile
Note that this requires Vagrant 2.0.2 or better.
> Upgrade to CentOS-7.4

- stoqs/loaders/CANON/loadCANON_may2018.py
- stoqs/mbari_campaigns.py
new loader for Spring CANON 2018 (May June). loadCANON_may2018.py
includes reference in the mbari_campaigns.py file
> new loader loadCANON_may2018.py Spring CANON 2018

- stoqs/loaders/CANON/loadCANON_os2016.py
- stoqs/loaders/load.py
- stoqs/mbari_campaigns.py
- stoqs/tools/check_opendap_urls.py
Attempting to make
```
SLACKTOKEN=... stoqs/loaders/load.py --test --slack
```
Give useful reports of the reusability of all data referenced from the load scrips in `mbari_campaigns.py`
> Improvements to master load.py script

- docker/requirements/base.txt
- stoqs/loaders/CANON/loadCANON_april2017.py
- stoqs/loaders/CANON/loadCANON_may2012.py
- stoqs/loaders/CANON/loadCANON_may2018_py3.py
- stoqs/loaders/CANON/loadCANON_os2015.py
- stoqs/loaders/CANON/loadCANON_os2016.py
- stoqs/loaders/CANON/loadCANON_os2018.py
- stoqs/loaders/CANON/loadCANON_postSeason2017.py
- stoqs/loaders/CANON/loadCANON_september2012.py
- stoqs/loaders/CANON/loadCANON_september2015.py
- stoqs/loaders/CANON/loadCANON_september2016.py
- stoqs/loaders/CANON/loadCANON_september2017.py
- stoqs/loaders/CCE/__init__.py
- stoqs/loaders/CCE/loadCCE_2015.py
- stoqs/loaders/DAPloaders.py
- stoqs/loaders/LakeMichigan/load_2016.py
- stoqs/loaders/MolecularEcology/loadSIMZ_oct2013.py
- stoqs/loaders/load.py
- stoqs/mbari_campaigns.py
This is being done to verify the __reusability__ of all data that we load into STOQS databases.
> Continue to fix loaders for reload of all databases on new server

- stoqs/loaders/CANON/__init__.py
- stoqs/loaders/CANON/loadCANON_may2018.py
fix typos in two files to add wg_Sparky
> fix typos to add wg_Sparky

- stoqs/loaders/CANON/__init__.py
- stoqs/loaders/CANON/loadCANON_april2011.py
- stoqs/loaders/DAPloaders.py
Applies to https://github.com/stoqs/stoqs/issues/735
> Fix older scripts to use loadLRAUV()

- stoqs/loaders/ROVCTD/ROVCTDloader.py
- stoqs/loaders/ROVCTD/loadTransectDives_mw97.sh
- stoqs/mbari_campaigns.py
Should be last set of loaders needed for final transition to the new kraken at MBARI.
> More ROVCTD Loader fixes

- stoqs/loaders/CANON/loadCANON_september2018.py
- stoqs/mbari_campaigns.py
add new loader file for CANON_september2018. Update mbari_campaigns.py to reflect this new campaign.
> create stoqs_canon_september2018 campaign

- stoqs/loaders/CANON/loadCANON_september2018.py
> update more nemesis loads to loadCANON_september2018.py

- .travis.yml
- README.md
- Vagrantfile
- docker/requirements/base.txt
- provision.sh
Applies to https://github.com/stoqs/stoqs/issues/774
> Help for hosts that don't support NFS file serving (e.g. Windows systems)

- stoqs/loaders/CANON/loadCANON_september2018.py
correct the start and end dates for a clean load of campaign
> startdate enddate updates to loadCANON_september2018.py loader

- README.md
- docker/postgis-pg_hba.sh
- provision.sh
- stoqs/loaders/CANON/loadCANON_september2018.py
Applies to https://github.com/stoqs/stoqs/issues/774
> Fixes for development system installation

- docker/docker-compose.yml
- docker/requirements/base.txt
- docker/requirements/development.txt
- docker/requirements/production.txt
- docker/stoqs-start.sh
- docker/template.env
- stoqs/loaders/load.py
- stoqs/stoqs/templates/stoqs/stoqsquery.html
- test.sh
Applies to https://github.com/stoqs/stoqs/issues/836
> Provide settings for docker deployment on MacOS

- stoqs/loaders/CANON/toNetCDF/__init__.py
- stoqs/loaders/CANON/toNetCDF/makeWFpctdNetCDF.sh
- stoqs/loaders/CANON/toNetCDF/pctdToNetcdf.py
- stoqs/loaders/seabird.py
> Fix Python 3 and Docker issues with pctdToNetcdf.py

- stoqs/loaders/CANON/toNetCDF/makeWFpctdNetCDF.sh
- stoqs/loaders/CANON/toNetCDF/makeWFuctdNetCDF.sh
- stoqs/loaders/CANON/toNetCDF/uctdToNetcdf.py
> Fix Python 3 and Docker issues with uctdToNetcdf.py

- docker/requirements/base.txt
- docker/requirements/development.txt
- stoqs/loaders/CANON/toNetCDF/makeWFpctdNetCDF.sh
- stoqs/loaders/CANON/toNetCDF/makeWFuctdNetCDF.sh
- stoqs/loaders/CANON/toNetCDF/uctdToNetcdf.py
> Fix shell scripts for processing CTD data locally and copying back to server

- stoqs/loaders/SampleLoaders.py
Applies to https://github.com/stoqs/stoqs/issues/840
> Log stopping times and warn if len(filterings) != len(stoppings)

- stoqs/loaders/SampleLoaders.py
- stoqs/loaders/__init__.py
Applies to https://github.com/stoqs/stoqs/issues/840
> Reverse order of ESP Sample matching, just warn() if no seq match

- docker/docker-compose.yml
- docker/template.env
- stoqs/loaders/SampleLoaders.py
> Make docker postgis data volumes use STOQS_VOLS_DIR variable

- docker/docker-compose.yml
- docker/requirements/development.txt
- docker/requirements/production.txt
- docker/template.env
> Revert back to separate POSTGRES_ variables

- docker/docker-compose.yml
- provision.sh
Applies to https://github.com/stoqs/stoqs/issues/846
> Update Vagrant provision.sh file

- docker/requirements/base.txt
- docker/requirements/development.txt
- docker/requirements/production.txt
- stoqs/loaders/seabird.py
Not really sure why this got removed 13 days ago in [this PR](https://github.com/stoqs/stoqs/pull/842/files). It's actually needed.
> Put the line.decode() back in

- stoqs/loaders/CANON/loadCANON_september2018.py
Update WFuctd and pctd nutrient samples to CANON_September2018. As loaded on development system and production system
> Update WFuctd and pctd nutrient samples to CANON_September2018

- stoqs/loaders/CANON/loadCANON_may2019.py
add makai to campaign platforms to load
> updates to loadCANON_may2019 campaign -- add makai

- stoqs/loaders/CANON/__init__.py
- stoqs/loaders/CANON/loadCANON_may2019.py
change name of wg_New to wg_272, and add NPS29 glider to campaign loader files.
> updates to loadCANON_may2019 campaign

- stoqs/loaders/SampleLoaders.py
- stoqs/loaders/lrauv_support.py
- stoqs/stoqs/templates/stoqs/activity.map
- stoqs/stoqs/templates/stoqs/stoqsquery.html
Also snuck in Sipper Sample loading code changes.
> UI usability fixes following colormap and LRAUV Mission display improvements

- stoqs/loaders/CANON/loadCANON_may2019.py
add nps29 glider to canon spring 2019 campaign
> add nps29 glider to canon spring 2019 campaign

- stoqs/loaders/CANON/loadCANON_fall2019.py
add nps29 spray glider to CANON fall 2019 loader
> add nps29 spray glider to CANON fall 2019 loader

- stoqs/stoqs/templates/stoqs/stoqsquery.html
> Fix permalink generation

- docker/requirements/base.txt
- stoqs/config/settings/common.py
- stoqs/utils/STOQSQManager.py
Seems to help fix problems identified in https://github.com/MBARIMike/stoqs/pull/727
> Log errors to console in production, fix SampleType assignment

- README.md
- docker/Dockerfile-stoqs
- docker/stoqs-start.sh
Should fix problem:
```
Step 1/16 : FROM pcic/geospatial-python
---> 8e26851956b9
Step 2/16 : MAINTAINER Mike McCann <mccann@xxx>
---> Using cache
---> fa2f1d823f19
Step 3/16 : ENV DEBIAN_FRONTEND noninteractive
---> Using cache
---> 04906b8a465f
Step 4/16 : RUN apt-get update &&     apt-get -qq -y install     firefox     freetds-dev     git     gmt     imagemagick     libncurses-dev     time     wget     xvfb
---> Running in b9b1ce0e5558
Ign:1 http://security.ubuntu.com/ubuntu cosmic-security InRelease
Err:2 http://security.ubuntu.com/ubuntu cosmic-security Release
404  Not Found [IP: 91.189.91.23 80]
```
> Inline cmds FROM pcic/geospatial-python, use ubuntu:19.10

- docker/requirements/base.txt
- stoqs/loaders/SampleLoaders.py
> Improve ESP Cartridge reporting with 'Disposition' report for each cartridge

- docker/docker-compose.yml
- docker/nginx.tmpl
- docker/template.env
- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/stoqs/views/__init__.py
- stoqs/utils/Parquet.py
- stoqs/utils/STOQSQManager.py
Applies to https://github.com/stoqs/stoqs/issues/837
> Refine Parquet estimate button operation

- doc/instructions/TIDBITS
- docker/nginx.tmpl
- stoqs/contrib/notebooks/select_data_in_columns_for_data_science.ipynb
- stoqs/contrib/notebooks/visualize_parquet.ipynb
- stoqs/contrib/parquet/stats.sh
- stoqs/stoqs/templates/stoqs/stoqsquery.html
- stoqs/stoqs/tests/unit_tests.py
- stoqs/utils/Parquet.py
Applies to https://github.com/stoqs/stoqs/issues/837 and https://github.com/stoqs/stoqs/issues/227.
> Notebook for example use of Parquet data 

- docker/stoqs-start.sh
- stoqs/contrib/notebooks/visualize_parquet.ipynb
- stoqs/loaders/DAPloaders.py
- stoqs/loaders/load.py
- stoqs/stoqs/tests/unit_tests.py
- stoqs/stoqs/views/wms.py
Applies to https://github.com/stoqs/stoqs/issues/837
> Notebook with download of parquet files from production server

- docker/requirements/base.txt
See https://github.com/django-extensions/django-extensions/issues/1750
> Revert to Django==4.0.6
